# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c8c5e9da4aac74b9927b366fad674218785cd232e139d64b0342c213ac3fbb86b604e5eae6da851708e4e50585a7b1e67894d98826a650c44eefbcff9c914ce

test:
  secret_key_base: 39a803aec313a15d6d10a82045df900e6af99b875b35d085de1f21ff3bdc6d55e7b9a350b6ceefcbc9d2b53837bf52aad2eed5d7ace9d67768e4e2be991dfdbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
